# -*- mode: yaml -*-

name: vaayu-env

dependencies:
  - python=2.7
  - pip
  - six
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipython
  - pyyaml
  - ruamel_yaml
  - ply
  - vtk
  - netcdf4
  - click
