# -*- coding: utf-8 -*-

"""Vaayu - Python Library for Wind Energy Applications
"""

from setuptools import setup
import os
import subprocess
from datetime import datetime

VERSION = "0.0.1"
ISDEV = True

basedir = os.path.dirname(__file__)

# https://github.com/numpy/numpy/blob/master/setup.py
def git_revision():
    """Return the Git SHA-ID if available"""
    def _minimal_ext_cmd(cmd):
        # construct minimal environment
        env = {}
        for k in ['SYSTEMROOT', 'PATH']:
            v = os.environ.get(k)
            if v is not None:
                env[k] = v
        # LANGUAGE is used on win32
        env['LANGUAGE'] = 'C'
        env['LANG'] = 'C'
        env['LC_ALL'] = 'C'
        out = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                               env=env).communicate()[0]
        return out

    try:
        out = _minimal_ext_cmd(['git', 'rev-parse', 'HEAD'])
        git_sha_id = out.strip().decode('ascii')
    except OSError:
        git_sha_id = "unknown"

    return git_sha_id

def write_version(fname="vaayu/version.py"):
    ver_txt = """#
# DO NOT EDIT!
# This file is automatically generated by setup
# Timestamp: %(timestamp)s+00:00
#
version = '%(version)s'
full_version = '%(full_version)s'
git_revision = '%(git_revision)s'
is_dev = %(is_dev)s

if is_dev:
    version = full_version
"""
    git_rev = git_revision()
    full_version = VERSION + '.dev-' + git_rev[:7]

    with open(fname,'w') as fh:
        fh.write(ver_txt % { 'version' : VERSION,
                             'full_version' : full_version,
                             'git_revision' : git_rev,
                             'is_dev' : str(ISDEV),
                             'timestamp' : datetime.utcnow().isoformat()})

write_version()

classifiers = [
    "Development Status :: 3 -Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Physics"
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Utilities",
]

setup(
    name="vaayu",
    version=VERSION,
    url="https://github.com/sayerhs/vaayu",
    license="Apache Lincense, Version 2.0",
    description="Vaayu - Python Library for Wind Energy Applications",
    long_description=__doc__,
    author="Shreyas Ananthan",
    author_email="shreyas@umd.edu",
    maintainer="Shreyas Ananthan",
    maintainer_email="shreyas@umd.edu",
    include_package_data=True,
    platforms="any",
    classifiers=classifiers,
    packages=[
        'vaayu',
        'vaayu.prelude',
        'vaayu.cfg',
    ],
)
